#Introduction to Python: CrossTalk November 2025


##Introduction

Python is a great general-purpose programming language on its own, but with the help of a few popular libraries (numpy, scipy, matplotlib) it becomes a powerful environment for scientific computing.

We expect that many of you will have some experience with Python and numpy; for the rest of you, this section will serve as a quick crash course both on the Python programming language and on the use of Python for scientific computing.

In this tutorial, we will cover:

* **Part I: Variables**: Store model settings and data
* **Part II: Lists**: Work with groups of data points
* **Part III: Control Flow**: Loops & conditional statements
* **Part IV: Functions**: Organize your code into steps
* **Part V: NumPy**: Do fast math on numbers
* **Part VI: Pandas**: Work with data tables

### Part I: Variables and Data Types

In [ ]:
# Strings
name = "John Smith"
department = "Data Science"

# Integers
age = 30
batch_size = 50000

# Floats
temperature = 25.5
learning_rate = 0.001

# Booleans
is_training = True
model_ready = False


In [ ]:
# Data Type checking
print("Type of name:", type(name))
print("Type of age:", type(temperature))

Type of name: <class 'str'>
Type of age: <class 'float'>


In [ ]:
# Conversion between types
number_text = "123"
number = int(number_text)
print("Converted number:", number, type(number))

Converted number: 123 <class 'int'>


#### Basic Operations

In [ ]:
# Arithmetic operations
a = 10
b = 5

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Exponent:", a ** 2)

Addition: 15
Subtraction: 5
Multiplication: 50
Division: 2.0
Exponent: 100


In [ ]:
# String operations
first_name = "John"
last_name = "Smith"
full_name = first_name + " " + last_name
print("Full name:", full_name)

Full name: John Smith


In [ ]:
# Exercise 1.1: Convert the string "98.6" to a float and store it in a variable called temperature
# Then print the temperature and its type


In [ ]:
# Exercise 1.2: Calculate BMI
# Given weight = 70 kg and height = 1.75 m
# Calculate BMI using formula: BMI = weight / (height ** 2)
# Print out the result


### Part II: Data Structures
There are different types of data structures in python such as **Lists**, **Tuples**, **Dictionaries**, **Sets**, and others. But in this tutorial we will focus on *Lists* and *Dictionaries*.

####Lists

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [ ]:
# List creation and manipulation
numbers = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

# Slicing
print("First three:", numbers[:3])
print("Last three:", numbers[-3:])
print("Middle section:", numbers[3:7])
print("Every second item:", numbers[::2])

First three: [10, 20, 30]
Last three: [80, 90, 100]
Middle section: [40, 50, 60, 70]
Every second item: [10, 30, 50, 70, 90]


In [ ]:
# List methods
numbers.append(110)  # Add to end
numbers.insert(0, 5)  # Insert at position
numbers.remove(30)  # Remove specific value
print("Modified list:", numbers)

popped = numbers.pop()  # Remove and return last item

print("Popped value:", popped)

Modified list: [5, 10, 20, 40, 50, 60, 70, 80, 90, 100, 110]
Popped value: 110


In [ ]:
# List comprehension
squares = [x**2 for x in range(1, 6)]

print("Squares:", squares)

Squares: [1, 4, 9, 16, 25]


In [ ]:
# Calculate statistics
maximum = max(numbers)
minimum = min(numbers)
total = sum(numbers)
average = total / len(numbers)

print ('average: ', average)

average:  52.5


In [ ]:
# Exercise 2.1: Create and manipulate a list
# Create a list of daily temperatures: [72, 75, 68, 70, 73, 71, 69]
# - Print the first 3 temperatures
# - Print the last 2 temperatures
# - Add a new temperature 74 to the end
# - Calculate and print the average temperature
# - create a new list containing only temperatures above 70. (NOTE: Use list comprehension)


You can find all the gory details about lists in the [documentation](https://docs.python.org/3/tutorial/datastructures.html).

####Dictionaries

A dictionary stores (key, value) pairs, similar to a `Map` in Java or an object in Javascript. You can use it like this:

In [ ]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary
print('cat' in d)     # Check if a dictionary has a given key; prints "True"

cute
True


In [ ]:
# Complex dictionary
student = {
    "name": "Alice Johnson",
    "age": 22,
    "courses": ["Math", "Physics", "Computer Science"],
    "grades": {"Math": 85, "Physics": 92, "Computer Science": 88},
    "contact": {
        "email": "alice@university.edu",
        "phone": "123-456-7890"
    }
}

# Accessing nested data
print("Student name:", student["name"])
print("Courses:", student["courses"])
print("Math grade:", student["grades"]["Math"])
print("Email:", student["contact"]["email"])


Student name: Alice Johnson
Courses: ['Math', 'Physics', 'Computer Science']
Math grade: 85
Email: alice@university.edu


In [ ]:
# Dictionary methods
print("Keys:", student.keys())
print("Values:", student.values())
print("Items:", student.items())

Keys: dict_keys(['name', 'age', 'courses', 'grades', 'contact'])
Values: dict_values(['Alice Johnson', 22, ['Math', 'Physics', 'Computer Science'], {'Math': 85, 'Physics': 92, 'Computer Science': 88}, {'email': 'alice@university.edu', 'phone': '123-456-7890'}])
Items: dict_items([('name', 'Alice Johnson'), ('age', 22), ('courses', ['Math', 'Physics', 'Computer Science']), ('grades', {'Math': 85, 'Physics': 92, 'Computer Science': 88}), ('contact', {'email': 'alice@university.edu', 'phone': '123-456-7890'})])


💡 Tip to remember:

() → do something (function or method call)

[] → get something (access data)

{} → make something (define dictionary or set)

In [ ]:
#Create a model configuration dictionary
model_config = {
    "model_name": "random_forest",
    "parameters": {
        "n_estimators": 100,
        "max_depth": 10,
        "random_state": 42
    },
}

print("Model configuration:")
print("Name:", model_config["model_name"])
print("Number of estimators:", model_config["parameters"]["n_estimators"])

Model configuration:
Name: random_forest
Number of estimators: 100


In [ ]:
# Exercise 2.2: Nested dictionary
# Create a hospital dictionary with:
# - "name": "City General Hospital"
# - "departments": {"Emergency": 45, "ICU": 20, "Surgery": 30}
# - "address": {"street": "123 Main St", "city": "Boston", "zip": "02101"}
# Print the number of ICU beds and the city


You can find all you need to know about dictionaries in the [documentation](https://docs.python.org/3/tutorial/datastructures.html#dictionaries).

### Part III: Control Flow (if, for, while)

Control flow statements in Python allow you to control the execution of code blocks. These include:  
- **Conditional statements (if/else)** to make decisions.  
- **For loops** to iterate over a sequence.  
- **While loops** to repeat a block of code as long as a condition is true.
- Usage of **"break" & "continue"**

We will practice these concepts with examples to understand how Python handles decision-making and repetition.

In [ ]:
# Complex conditions
temperature = 75
humidity = 60

if temperature > 80 and humidity > 70:
    print("Hot and humid")
elif 60 <= temperature <= 80 and humidity <70:
    print("Pleasant weather")
else:
    print("Cool weather")

Pleasant weather


In [ ]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# For loop with "break" example
for num in numbers:
    if num > 5:
        break
    print(num)

1
2
3
4
5


In [ ]:
# For loop with "continue" example

for num in numbers:
    if num < 5:
        continue
    print(num)

5
6
7
8
9
10


In [ ]:
# While loop with condition
count = 0
while count < 5:
    print("Count:", count)
    count += 1

Count: 0
Count: 1
Count: 2
Count: 3
Count: 4


In [ ]:
#Process data until condition
data_stream = [23, 45, -1, 67, 32, -1, 89, 54]

valid_data = []
for value in data_stream:
    if value == -1:  # Sentinel value
        print("End of stream reached")
        break
    valid_data.append(value)
    print("Processed:", value)

print("Valid data collected:", valid_data)

Processed: 23
Processed: 45
End of stream reached
Valid data collected: [23, 45]


In [ ]:
# Exercise 3.1: Temperature classification
# Write code that classifies a temperature as:
# - "Fever" if >= 100.4
# - "Normal" if between 97 and 100.3
# - "Low" if < 97
# Test with temperature = 98.6


In [ ]:
# Exercise 3.2: Process patient ages
# Given the list of ages below:
# - Use a for loop to count how many patients are:
#   * Under 18 (pediatric)
#   * Between 18-65 (adult)
#   * Over 65 (senior)
# Print the counts

ages = [12, 25, 45, 67, 34, 8, 72, 56, 15, 81, 42, 19]


In [ ]:
# Exercise 3.3: While loop - countdown
# Create a countdown from 10 to 1
# Print each number and "Liftoff!" at the end


### Part IV: Functions

Functions help us organize code into reusable blocks. They take inputs (arguments), perform actions, and return results.  
In this section, we will learn how to define and call functions, pass parameters, and return values.


In [ ]:
def greet(name):
    """Function to greet a person"""
    return f"Hello, {name}! Welcome to CrossTALK Bootcamp!"

def add_numbers(a, b):
    """Function to add two numbers"""
    return a + b

# Calling functions
print(greet("Data Scientist"))

print(add_numbers(10, 20))



Hello, Data Scientist! Welcome to CrossTALK Bootcamp!
30


In [ ]:
#Using nested if-statements in a "function"
def validate_data_point(value):
    if isinstance(value, (int, float)):
        return "Valid positive number" if value >= 0 else "Invalid: Negative number"

    elif isinstance(value, str):
        return "Valid text" if len(value) > 0 else "Invalid: Empty text"

    return "Unknown data type"

# Test the function
print(validate_data_point(25))
print(validate_data_point(-5))
print(validate_data_point("Hello"))
print(validate_data_point(""))

Valid positive number
Invalid: Negative number
Valid text
Invalid: Empty text


We will often define functions to take optional keyword arguments, like this:

In [ ]:
# Default arguments and keyword arguments
def create_model(name, layers=3, activation='relu', dropout=0.2):
    model_config = {
        'name': name,
        'architecture': {
            'layers': layers,
            'activation': activation,
            'dropout': dropout
        }
    }
    return model_config

# Different ways to call the function
model1 = create_model("simple_nn")
model2 = create_model("deep_nn", layers=5, dropout=0.5)
model3 = create_model("custom_nn", activation='sigmoid', layers=4)

print("Model 1:", model1)
print("Model 2:", model2)
print("Model 3:", model3)

Model 1: {'name': 'simple_nn', 'architecture': {'layers': 3, 'activation': 'relu', 'dropout': 0.2}}
Model 2: {'name': 'deep_nn', 'architecture': {'layers': 5, 'activation': 'relu', 'dropout': 0.5}}
Model 3: {'name': 'custom_nn', 'architecture': {'layers': 4, 'activation': 'sigmoid', 'dropout': 0.2}}


In [ ]:
# Exercise 4.1: Temperature converter
# Write a function celsius_to_fahrenheit(celsius) that:
# - Converts Celsius to Fahrenheit using formula: F = (C * 9/5) + 32
# - Returns the result
# Test with 37°C (normal body temperature)


In [ ]:
# Exercise 4.3: Grade classifier function
# Write a function classify_grade(score) that returns:
# - "A" if score >= 90
# - "B" if score >= 80
# - "C" if score >= 70
# - "D" if score >= 60
# - "F" if score < 60
# Test with multiple scores


## Part V: Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

To use Numpy, we first need to import the `numpy` package:

In [2]:
import numpy as np

###Arrays

A numpy array is a grid of values, all of the same type. It allows element-wise operations, which makes computation efficient and concise.

In this section, we will learn how to create NumPy arrays and perform basic operations on them.


In [ ]:
# We can initialize numpy arrays from nested Python lists:

# Creating 1D array
arr = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr)

# Creating 2D array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 7]])
print("\n2D Array (Matrix):\n", matrix)

# Checking data type and shape
print("\nArray Data Type:", arr.dtype)
print("Matrix Shape:", matrix.shape)

# Basic statistics
print("Sum of Array:", arr.sum())
print("Mean of Array:", arr.mean())

1D Array: [1 2 3 4 5]

2D Array (Matrix):
 [[1 2 3]
 [4 5 7]]

Array Data Type: int64
Matrix Shape: (2, 3)
Sum of Array: 15
Mean of Array: 3.0


NumPy arrays allow element-wise operations, which makes computation efficient and concise.

In [ ]:
# Element-wise arithmetic operations
print("Add 10 to each element:", arr + 10)
print("Square of each element:", arr ** 2)
print("Multiply by 3:", arr * 3)

# Matrix multiplication (dot product)
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 3]])
print("\nMatrix A:\n", a)
print("Matrix B:\n", b)
print("Matrix Multiplication (A * B):\n", np.dot(a, b))

Add 10 to each element: [11 12 13 14 15]
Square of each element: [ 1  4  9 16 25]
Multiply by 3: [ 3  6  9 12 15]

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[2 0]
 [1 3]]
Matrix Multiplication (A * B):
 [[ 4  6]
 [10 12]]


In [6]:
# What happens if we including different datatypes in an array?


In [5]:
# The data in an array must be rectangular (i.e., same number of column):


###Array indexing

Just like lists in Python, NumPy arrays can be indexed and sliced to access specific elements or subarrays.
We will learn how to retrieve specific elements, rows, and columns from NumPy arrays.

In [ ]:
import numpy as np

# Indexing
print("First element of array:", arr[0])
print("Last element of array:", arr[-1])

# Slicing
print("First three elements:", arr[:3])
print("Elements from index 2 onwards:", arr[2:])
print("Every second element:", arr[::2])

# Indexing in 2D array
print("\nElement at (0,1):", matrix[0, 1])
print("First row:", matrix[0, :])
print("Second column:", matrix[:, 1])

First element of array: 1
Last element of array: 5
First three elements: [1 2 3]
Elements from index 2 onwards: [3 4 5]
Every second element: [1 3 5]

Element at (0,1): 2
First row: [1 2 3]
Second column: [2 5]


NumPy offers many built-in functions for creating arrays, generating random numbers, and performing mathematical operations.
In this section, we will explore functions like **zeros**, **ones**, **arange**, and **random**.

In [ ]:
# Array of zeros
zeros_array = np.zeros((2, 3))
print("Array of Zeros:\n", zeros_array)

# Array of ones
ones_array = np.ones((3, 3))
print("\nArray of Ones:\n", ones_array)

# Array with a range of values
range_array = np.arange(0, 10, 2)
print("\nArray with range (0 to 10 with step 2):", range_array)

# Random array
random_array = np.random.rand(2, 4)  # 2x4 matrix with random values between 0 and 1
print("\nRandom Array (2x4):\n", random_array)

# Random integers
rand_int_array = np.random.randint(1, 100, size=(3, 3))
print("\nRandom Integers (3x3, 1 to 100):\n", rand_int_array)

Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array with range (0 to 10 with step 2): [0 2 4 6 8]

Random Array (2x4):
 [[0.15028901 0.3206483  0.11955891 0.65553941]
 [0.72367252 0.00503096 0.82224139 0.21715749]]

Random Integers (3x3, 1 to 100):
 [[71 40 70]
 [28 10  1]
 [66 91 15]]


In [ ]:
# Exercise 5.1: 2D array (matrix)
# Create a 3x4 matrix of random integers between 50 and 100
# Print:
# - The entire matrix
# - The shape of the matrix
# - The mean of all values
# - The second row


In [ ]:
# Exercise 5.2: Boolean indexing
# TODO: Given the array below, create a new array containing only values > 100
# Print both arrays

lab_results = np.array([95, 110, 88, 125, 102, 115, 92, 130, 98])


## Part VI: Reading and Writing Data

Pandas allows us to easily read data from files (like CSV, Excel) and write data to files.  
We will practice reading data into Pandas DataFrames and saving them to files.



> **📌 Note:**
>
> **When reading from or writing to files (CSV, Excel), it is important to define the correct file path.**
>
> - If your file is in the **same directory** as your Jupyter Notebook, you can simply use the file name, e.g., `'myfile.csv'`.
> - If your file is located elsewhere on your computer, you should use an **absolute path**, e.g., `'/Users/username/Documents/myfile.csv'` (on Mac/Linux) or `'C:\\Users\\username\\Documents\\myfile.csv'` (on Windows).
> - **In Google Colab**, you need to **upload files manually** or **mount Google Drive** to access files.
>
> **Example paths:**
>
> - `'data.csv'` (same directory as notebook)
> - `'/Users/username/Desktop/data.csv'` (absolute path on Mac/Linux)
> - `'C:\\Users\\username\\Desktop\\data.csv'` (absolute path on Windows)
>
> ➤ **Tip:** Use `'index=False'` when saving DataFrames to prevent Pandas from writing row numbers as a column in the file.


In [ ]:
import pandas as pd
# Sample healthcare-related data
data = {
    "Patient_ID": [101, 102, 103, 104, 105],
    "Age": [45, 62, 37, 29, 54],
    "Gender": ["Female", "Male", "Female", "Male", "Female"],
    "Diagnosis": ["Diabetes", "Hypertension", "Healthy", "Asthma", "Diabetes"],
    "Treatment_Cost": [5000, 7000, 1500, 3000, 4500]
}

# Create DataFrame
df = pd.DataFrame(data)
print("Healthcare Dataset:\n", df)

Healthcare Dataset:
    Patient_ID  Age  Gender     Diagnosis  Treatment_Cost
0         101   45  Female      Diabetes            5000
1         102   62    Male  Hypertension            7000
2         103   37  Female       Healthy            1500
3         104   29    Male        Asthma            3000
4         105   54  Female      Diabetes            4500


In [ ]:
# Reading and Writing Data (Healthcare Dataset)

print("\n### Reading and Writing Data with Pandas (Healthcare Dataset) ###\n")

# --- Writing Data ---

# Define paths (adjust paths based on your working environment)
csv_path = 'healthcare_data.csv'
excel_path = 'healthcare_data.xlsx'

# Save to CSV
df.to_csv(csv_path, index=False)
print(f"DataFrame saved to '{csv_path}'")

# Save to Excel
df.to_excel(excel_path, index=False, sheet_name='Patients')
print(f"DataFrame saved to '{excel_path}'")

# --- Reading Data ---

# Read CSV
df_csv = pd.read_csv(csv_path)
print("\nDataFrame loaded from CSV:\n", df_csv)

# Read Excel
df_excel = pd.read_excel(excel_path, sheet_name='Patients')
print("\nDataFrame loaded from Excel:\n", df_excel)

# --- Note for students ---

print("\nIMPORTANT NOTE:")
print("- Make sure to set correct file paths when reading/writing.")
print("- Use relative paths like 'healthcare_data.csv' if in the same folder as notebook.")
print("- Use absolute paths if files are located elsewhere on your system.")


### Reading and Writing Data with Pandas (Healthcare Dataset) ###

DataFrame saved to 'healthcare_data.csv'
DataFrame saved to 'healthcare_data.xlsx'

DataFrame loaded from CSV:
    Patient_ID  Age  Gender     Diagnosis  Treatment_Cost
0         101   45  Female      Diabetes            5000
1         102   62    Male  Hypertension            7000
2         103   37  Female       Healthy            1500
3         104   29    Male        Asthma            3000
4         105   54  Female      Diabetes            4500

DataFrame loaded from Excel:
    Patient_ID  Age  Gender     Diagnosis  Treatment_Cost
0         101   45  Female      Diabetes            5000
1         102   62    Male  Hypertension            7000
2         103   37  Female       Healthy            1500
3         104   29    Male        Asthma            3000
4         105   54  Female      Diabetes            4500

IMPORTANT NOTE:
- Make sure to set correct file paths when reading/writing.
- Use relative paths like 'h

In [ ]:
# package to efficiently read in data from parquet file
from pyarrow.parquet import ParquetFile
import pyarrow as pa

# GitHub raw file URL
github_url = 'https://github.com/AzizAbusaleh/CrossTalk2025/raw/main/dataSet.parquet'

# Read directly from URL
train_data = pd.read_parquet(github_url)

# Display first 5 rows
train_data.head(5)

ID           DEL_ID  DELLabel  RawCount Target  \
0  22010204180211  L22-102-418-211         0         0  WDR91   
1  30023100530730   L30-231-53-730         0         0  WDR91   
2  30004703160748   L30-47-316-748         0         0  WDR91   
3  30004200250347    L30-42-25-347         0         0  WDR91   
4  22002800290407    L22-28-29-407         0         0  WDR91   

                                               ECFP4  \
0  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...   
1  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...   
2  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...   
3  0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...   
4  0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,...   

                                               ECFP6  \
0  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,...   
1  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,...   
2  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...   
3  0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...   
4  0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,...   

                                               FCFP4  \
0  12,1,2,0,18,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...   
1  12,2,6,0,14,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,...   
2  10,1,2,0,16,0,4,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,...   
3  12,2,3,0,14,0,3,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,...   
4  8,2,3,0,17,1,2,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0...   

                                               FCFP6  \
0  12,1,2,0,18,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...   
1  12,2,6,0,14,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,...   
2  10,1,2,0,16,0,4,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,...   
3  12,2,3,0,14,0,3,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,...   
4  8,2,3,0,17,1,2,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0...   

                                               MACCS  \
0  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,...   
1  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...   
2  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...   
3  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...   
4  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,...   

                                                 RDK  \
0  1,1,1,0,1,1,0,0,1,0,1,1,0,1,1,1,0,0,1,1,0,0,1,...   
1  1,1,0,1,1,1,1,1,0,1,1,1,0,1,0,1,1,1,0,1,0,1,1,...   
2  1,1,1,1,0,1,1,1,1,1,1,1,0,1,1,0,1,0,0,1,0,0,0,...   
3  1,0,0,0,0,1,0,1,0,0,0,1,0,0,1,1,1,0,1,0,0,0,0,...   
4  1,1,0,1,1,1,1,1,1,1,1,1,0,0,1,0,1,1,0,1,0,1,0,...   

                                              AVALON  \
0  0,0,0,1,2,0,0,0,0,0,0,0,0,0,0,15,0,3,0,0,0,0,0...   
1  0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,22,0,0,0,0,0,1,2...   
2  1,0,0,1,4,0,1,0,0,0,0,0,0,0,0,14,0,0,0,0,0,0,0...   
3  0,0,0,0,4,0,0,0,0,0,0,0,0,0,1,11,0,0,0,0,0,0,0...   
4  1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,9,0,0,0,0,0,0,0,...   

                                            ATOMPAIR  \
0  1,0,0,0,3,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,...   
1  0,0,0,0,2,1,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,...   
2  0,0,0,0,1,0,0,1,0,0,0,2,0,0,0,0,0,0,0,0,0,0,3,...   
3  0,1,0,1,3,0,0,1,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,...   
4  0,1,0,0,4,0,0,0,0,0,0,5,4,0,0,0,0,0,0,0,0,0,0,...   

                                              TOPTOR   MW  ALOGP  
0  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...  493    3.4  
1  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...  494    3.4  
2  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...  494    3.4  
3  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...  494    3.4  
4  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...  495    3.4